[package]
name = "waterui-cli"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
console = "0.16.1"
ctrlc = "3.5.0"
dialoguer = "0.12.0"
heck = "0.5.0"
home = "0.5.11"
include_dir = "0.7.4"
notify = { version = "8.2.0", default-features = false, features = ["macos_kqueue"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
toml = "0.9.8"
tracing.workspace = true
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "fmt", "json"] }
walkdir = "2.5.0"
which = "8.0.0"
crates-index = "3.11.0"
semver = "1.0.27"
webbrowser = "1.0.5"
color-eyre = { version = "0.6.5", features = ["issue-url"] }
tokio = { version = "1", features = ["full"] }
hyper = { version = "1.8.1", features = ["http1", "server"] }
hyper-util = { version = "0.1.18", features = ["http1", "server", "tokio"] }
http-body-util = "0.1.3"
mime_guess = "2.0.5"
bytes = "1.9.0"
futures-util = "0.3.31"
indexmap = "2.6.0"
tungstenite = "0.23"
tokio-tungstenite = "0.23"
thiserror = "2.0.17"
smol = "2.0.2"
atty = "0.2.14"
pathdiff = "0.2.1"
zenwave.workspace = true

[[bin]]
name = "water"
path = "src/terminal/main.rs"


[target.'cfg(target_os = "macos")'.dependencies]
which = "8.0.0"


[lints]
workspace = true
