[package]
name = "form-example"
version = "0.1.0"
edition = "2024"
authors = ["Lexo Liu"]

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
waterui = { path = "../.." }
waterui-ffi = { path = "../../ffi" }

[workspace]
