[package]
name = "demo"
version = "0.1.0"
edition = "2024"
authors = ["lexoliu"]

[dependencies.waterui]
path = "/Users/lexoliu/Coding/waterui"

[dependencies.waterui-ffi]
path = "/Users/lexoliu/Coding/waterui/ffi"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[workspace]
