[package]
name = "canvas-demo"
version = "0.1.0"
edition = "2024"
authors = ["Lexo Liu"]

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
waterui = { workspace = true, features = ["graphics"] }
waterui-ffi.workspace = true